# Generated by Django 2.1.7 on 2019-06-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0020_remove_good_get_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good_get',
            name='Photo',
        ),
        migrations.AddField(
            model_name='good_get',
            name='Price',
            field=models.IntegerField(default='0'),
        ),
    ]
