# Generated by Django 2.1.7 on 2019-06-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0021_auto_20190615_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='good_get',
            name='Photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
