# Generated by Django 2.1.7 on 2019-06-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0022_good_get_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='good_get',
            name='Available',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='good_get',
            name='Name',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AlterField(
            model_name='good_get',
            name='Photo',
            field=models.ImageField(default=' ', upload_to=''),
        ),
    ]
