# Generated by Django 2.1.7 on 2019-06-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0023_auto_20190624_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good_get',
            name='Available',
        ),
        migrations.RemoveField(
            model_name='good_get',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='good_get',
            name='Price',
        ),
    ]
