# Generated by Django 2.1.7 on 2019-06-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0024_auto_20190624_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='good_get',
            name='Photo',
            field=models.ImageField(default=' ', upload_to=''),
        ),
        migrations.AddField(
            model_name='good_get',
            name='Price',
            field=models.IntegerField(default='0'),
        ),
    ]
