# Generated by Django 2.1.7 on 2019-06-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0026_auto_20190625_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='good_get',
            name='Photo',
            field=models.ImageField(default=' ', upload_to=''),
        ),
    ]
