# Generated by Django 2.1.7 on 2019-06-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0029_auto_20190627_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGood',
        ),
    ]
