# Generated by Django 2.1.7 on 2019-06-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0030_delete_usergood'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGood',
            fields=[
            ],
            options={
                'ordering': ('Size', 'Name', 'Photo', 'Price'),
                'proxy': True,
                'indexes': [],
            },
            bases=('HiPage.good_get',),
        ),
    ]
