# Generated by Django 2.1.7 on 2019-06-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0032_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
