# Generated by Django 2.1.7 on 2019-06-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0033_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
